'use strict';
const $ = s => document.querySelector(s);

const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const commands = {
 status:['연결 상태','설치된 게임과 연결을 확인합니다.'],
 capabilities:['지원 기능','현재 게임 버전이 제공하는 명령과 사양입니다.'],
 get_current_environment:['위치와 환경','현재 지역, 날씨, 에린 시간과 마이홈 상태를 확인합니다.'],
 get_my_info:['캐릭터 정보','레벨, 직업, 능력치와 현재 컨디션을 확인합니다.'],
 get_activity:['현재 행동','이동, 전투, 연주와 상호작용 상태를 확인합니다.'],
 get_quests:['진행 중 퀘스트','현재 활성 퀘스트 추적 탭에 표시된 항목입니다.'],
 get_daily_missions:['일일 미션','캐릭터의 오늘 목표와 보상 수령 여부입니다.'],
 get_weekly_missions:['주간 미션','계정의 이번 주 목표와 진행도입니다.'],
 get_currencies:['보유 재화','주요 재화의 현재 보유량입니다.'],
 get_inventory:['가방 무게','현재 가방 무게와 최대 무게를 확인합니다.'],
 get_items:['아이템 목록','가방과 창고의 재료·음식·소모품입니다. 장비·의상·펫은 포함되지 않습니다.','items'],
 get_near_npcs:['주변 NPC','반경 30 이내 대화 가능한 NPC와 동료를 확인합니다.'],
 get_near_pcs:['주변 모험가','주변 모험가의 공개된 상태와 연주 정보를 확인합니다.'],
 get_gatherable_items:['채집 가능한 재료','생활 레벨 조건을 충족한 아이템입니다. 도구가 준비된 대상을 선택하세요.','filter'],
 execute_gathering:['채집 시작','지정 아이템을 최대 100개까지 채집합니다. 낚시는 직접 중단할 때까지 계속됩니다.','action','get_gatherable_items','displayName',5],
 get_alterable_items:['가공 레시피','재료, 생산량과 가공 가능 여부를 확인합니다.','filter'],
 execute_altering:['가공 등록','시설로 이동해 가공 작업 1건을 등록합니다. 완료 후 수령은 별도입니다.','action','get_alterable_items','displayName',5],
 get_altering_works:['가공 작업 현황','모든 시설의 대기·진행·완료 작업입니다. 완료된 항목에서 수령할 수 있습니다.'],
 complete_altering_work:['가공품 수령','선택한 품목이 있는 시설로 이동해 그 시설의 완료 작업을 모두 수령합니다.','action','get_altering_works','displayName'],
 get_craftable_items:['제작 레시피','재료, 생산량과 제작 가능 여부를 확인합니다.','filter'],
 execute_crafting:['제작 실행','시설로 이동해 지정 횟수만큼 제작하고 결과를 수령합니다.','action','get_craftable_items','displayName',5],
 get_instruments:['보유 악기','악기의 내구도와 장착 여부를 확인합니다.','filter'],
 change_instrument:['악기 장착','선택한 보유 악기를 장착합니다.','action','get_instruments','name'],
 get_music_scores:['보유 악보','보유 악보의 제목, 보관 위치와 복사 허용 여부입니다.','filter'],
 play_music_score:['악보 연주','선택한 악보를 연주합니다. 악기 장착이 필요합니다.','action','get_music_scores','title'],
 get_social_actions:['행동과 표정','목록의 실제 명령을 선택해 행동하거나 표정을 바꿉니다.','filter'],
 write_chat:['채팅 / 행동 실행','최대 50자의 일반 채팅 또는 목록에서 선택한 행동·표정을 실행합니다.','chat'],
 stop_action:['행동 중단','채집, 자동 이동·플레이, 연주 등 중단 가능한 현재 행동을 멈춥니다.','action'],
 stand_up:['일어나기','/앉기로 앉은 캐릭터를 일으킵니다. 의자에 앉은 상태는 행동 중단을 사용하세요.','action']
};
const groups = {
 home:['대시보드','⌂',[]],
 adventure:['모험 정보','♧',['get_my_info','get_current_environment','get_activity','get_quests','get_daily_missions','get_weekly_missions','get_near_npcs','get_near_pcs']],
 bag:['가방과 재화','▤',['get_items','get_inventory','get_currencies']],
 gather:['채집과 낚시','♧',['get_gatherable_items','execute_gathering']],
 workshop:['제작과 가공','◇',['get_craftable_items','execute_crafting','get_alterable_items','execute_altering','get_altering_works','complete_altering_work']],
 music:['음악과 소셜','♫',['get_instruments','change_instrument','get_music_scores','play_music_score','get_social_actions','write_chat','stand_up','stop_action']],
 catalog:['전체 지원 기능','≡',['capabilities','status']]
};
const labels={DisplayName:'이름',DisplayTitle:'악보 제목',Name:'이름',Title:'타이틀',RealmName:'서버',Level:'레벨',EnabledCombatJobDisplayName:'직업',CombatScore:'전투력',LivingScore:'생활력',AttractivenessScore:'매력',DecorScore:'장식 점수',Vitals:'현재 컨디션',HealthCurrent:'현재 생명력',HealthMax:'최대 생명력',ShieldAmount:'보호막',ShieldMax:'최대 보호막',SatietyValue:'포만감',SatietyMax:'최대 포만감',SatietyRatio:'포만감 비율',InventoryWeightCurrent:'가방 무게',InventoryWeightMax:'최대 가방 무게',ActiveBuffCount:'활성 버프 수',ChannelDisplayName:'채널',GameSpaceDisplayName:'지역',WorldPosition:'위치',Weather:'날씨',ErinnNow:'에린 시간',Housing:'마이홈',IsInHousing:'마이홈 내부',IsOwnedHousing:'내 마이홈',CanEnterHousing:'마이홈 입장 가능',CannotEnterHousingReason:'입장 불가 사유',CanExitHousing:'퇴장 가능',CurrentInventoryWeight:'현재 무게',CurrentInventoryWeightAsDecimal:'현재 무게',MaxInventoryWeight:'최대 무게',MaxInventoryWeightAsDecimal:'최대 무게',Count:'수량',Location:'보관 위치',IsLocked:'잠금',CategoryDisplayName:'분류',Amount:'보유량',ToolOk:'도구 준비',Craftable:'제작 가능',Alterable:'가공 가능',ProducedPerCraft:'1회 생산량',ProducedPerWork:'작업당 생산량',MissingIngredients:'부족한 재료',Required:'필요',Owned:'보유',Reason:'사유',Durability:'내구도',IsEquipped:'장착',IsCopyingAllowed:'복사 허용',Distance:'거리',FacilityName:'시설',State:'상태',RemainingSeconds:'남은 시간(초)',IsCompleted:'완료',IsRewardReceived:'보상 수령',CurrentCount:'현재',GoalCount:'목표',Description:'설명',Objectives:'목표',QuestTitle:'퀘스트',SourceDisplayName:'분류',IsFriend:'친구',IsInParty:'파티',HasGuild:'길드 가입',IsSameGuild:'같은 길드',IsCoOwner:'마이홈 공동 소유',IsInCombat:'전투 중',Performance:'연주',IsPlaying:'연주 중',InstrumentName:'악기',MusicTitle:'곡',IsLoop:'반복',ElapsedSeconds:'경과 시간(초)',TotalDurationSeconds:'전체 길이(초)',ChannelCount:'채널 수',autoPlay:'자동 플레이',autoTravel:'자동 이동',combatState:'전투',dialogue:'대화',Dungeon:'던전',Battlefield:'전장',Tutorial:'튜토리얼',Scenario:'시나리오',Interaction:'상호작용',Mode:'조작 상태',IsAutoPlaying:'자동 플레이 중',AutoPlayTargetDisplayName:'대상',IsAutoTraveling:'이동 중',IsDead:'사망',IsReviving:'부활 중',HasTarget:'대상 있음',HasShortcut:'바로가기 지원',gained:'획득 수량',target:'채집 목표',result:'결과',message:'안내',cost:'소비 내역',rewards:'획득 보상',criticalRewards:'추가 보상',craftCount:'제작 횟수',collected:'수령',kind:'확인할 화면',completedCount:'수령 가능 작업',craftingUnlocked:'제작 기능 해금',pipe:'연결',PaladinStats:'팔라딘 능력치'};
const values={Sunny:'맑음',Rain:'비',Rainy:'비',Cloudy:'흐림',Snow:'눈',inventory:'가방',account_storage:'계정 창고',character_storage:'캐릭터 창고',Completed:'완료',InProgress:'진행 중',NotStarted:'대기',connected:'연결됨',completed:'완료',started:'시작됨',stopped:'중단됨',stopped_by_user:'사용자 중단'};
const errors={not_enough_currency:'정령의 날개가 부족합니다.',tool_missing:'필요한 도구가 없습니다.',tool_broken:'도구 내구도가 소진되었습니다.',overweight:'가방 무게를 줄여 주세요.',not_in_field:'필드에서 다시 시도하세요.',blocked:'게임에 표시된 확인 화면을 처리해 주세요.',not_found:'대상을 찾지 못했습니다. 목록을 다시 조회하세요.',invalid_state:'중단할 수 있는 행동이 없습니다.',not_sitting:'현재 /앉기 상태가 아닙니다.',no_instrument:'먼저 악기를 장착하세요.',insufficient_living_skill_level:'생활 레벨이 부족합니다.',not_available_on_combat:'전투 중에는 사용할 수 없습니다.',not_available_on_dead:'사망 상태에서는 사용할 수 없습니다.',not_available_on_riding:'탑승 중에는 사용할 수 없습니다.',rate_limited:'요청이 너무 빠릅니다. 잠시 후 다시 시도하세요.',insufficient_facility_level:'시설 레벨이 부족합니다.',not_enough_ingredient:'재료가 부족합니다.',ingredient_locked:'재료가 잠겨 있습니다.',insufficient_transfer_cost:'재료 이동 비용이 부족합니다.',no_route:'이동 경로를 찾지 못했습니다.',required_consumable_missing:'필요한 소모품이 없습니다.',requires_user_interaction:'이 작업은 게임에서 직접 시작해야 합니다.',insufficient_decor_score:'장식 점수가 부족합니다.',not_available:'현재 실행할 수 없습니다.',crafting_locked:'제작 기능이 해금되지 않았습니다.',invalid_count:'제작 횟수가 허용 범위를 벗어났습니다.',cost_payment_failed:'정령의 날개 소비에 실패했습니다.',no_completed_work:'완료된 가공 작업이 없습니다.',no_completed_work_at_facility:'해당 시설에 완료된 작업이 없습니다.',not_completed_yet:'아직 작업이 완료되지 않았습니다.',no_altering:'가공 작업이 없습니다.',timeout:'게임 응답이 시간 내에 완료되지 않았습니다.',canceled:'작업이 중단되었습니다.'};
let state={jobs:[],available:[],catalog:{}}, cache={}, handled=new Set(), waiters=new Map(), view='home', current='', page=0, rawData=null, online=false, pollTimer, busyPolling=false, confirmationBusy=false, stopped=false;
const actionCmd=c=>commands[c]?.[2]==='action'||c==='write_chat';
const val=v=>v&&typeof v==='object'&&'Value'in v?v.Value:v;
const text=v=>typeof v==='boolean'?(v?'예':'아니오'):v===null?'—':typeof v==='number'?v.toLocaleString('ko-KR'):values[v]||String(v??'—');
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,5000)}
async function api(path,body){return window.bridgeFetch(path,body)}
function go(group,command){view=group;current=command||groups[group][2][0]||'';page=0;location.hash=group;render();}
function navigateCommand(command){const group=Object.keys(groups).find(g=>groups[g][2].includes(command));go(group||'catalog',command)}
async function request(command,body='',confirmed=false){const result=await api('/api/run',{command,body,confirmed});pollSoon();return new Promise((resolve,reject)=>waiters.set(result.id,{resolve,reject}))}
function pollSoon(){clearTimeout(pollTimer);pollTimer=setTimeout(poll,150)}
async function poll(){if(stopped||busyPolling||!window.bridgeSettings.token)return;busyPolling=true;try{state=await api('/api/state');for(const j of state.jobs){if(j.state!=='running'&&!handled.has(j.id)){handled.add(j.id);cache[j.command]=j;const pending=waiters.get(j.id);if(pending){waiters.delete(j.id);pending.resolve(j)}if(j.command==='status'){online=j.ok&&j.data?.pipe==='connected';updateConnection()}if(view==='home')renderHome();else if(current===j.command)renderResults();if(actionCmd(j.command))toast(`${commands[j.command][0]}: ${jobStatus(j)}`)}}updateDock();if($('#historyDialog').open)renderHistory()}catch(e){if(stopped)return;$('#connection').textContent='앱 연결 끊김';$('#connection').className='connection';for(const [id,p]of waiters){p.reject(e);waiters.delete(id)}$('#banner').hidden=false;$('#banner').textContent='로컬 앱에 연결할 수 없습니다. 로컬 서버 연결 버튼에서 서버와 연결 키를 확인하세요.'}finally{busyPolling=false;clearTimeout(pollTimer);if(!stopped)pollTimer=setTimeout(poll,state.jobs.some(j=>j.state==='running')?600:3000)}}
function jobStatus(j){return {running:'진행 중',succeeded:'완료',failed:'실패',stopped:'중단됨',unknown:'상태 확인 필요'}[j.state]||j.state}
function updateConnection(){$('#connection').textContent=online?'게임 연결됨':'게임 연결 안 됨';$('#connection').className=`connection ${online?'ok':''}`;$('#banner').hidden=online;if(!online)$('#banner').textContent='게임에 접속하고 AI 커넥터를 켜 주세요. 경로를 찾지 못했다면 연결 설정을 확인하세요.'}
async function connect(){if(!window.bridgeSettings.token){window.showBridge();return;}const b=$('#connectButton');b.disabled=true;try{await request('status');await request('capabilities');if(online){await request('get_current_environment');await request('get_my_info');await request('get_inventory');}render()}catch(e){toast(e.message)}finally{b.disabled=false}}
function updateDock(){const active=state.jobs.filter(j=>j.state==='running');const action=active.find(j=>actionCmd(j.command));const j=action||active[0];$('#historyCount').textContent=state.jobs.length;$('#jobTitle').textContent=j?`${commands[j.command]?.[0]||j.command} 진행 중`:state.unknownAction?'게임 상태를 확인해 주세요':'새로운 요청을 할 수 있습니다';$('#jobSubtitle').textContent=j?`${Math.max(0,Math.floor(Date.now()/1000-j.started))}초 경과 · 화면 이동과 조회가 가능합니다`:'중단 버튼은 게임에서 진행 중인 행동에도 사용할 수 있습니다.';$('#activityIcon').innerHTML=j?'<span class="spinner"></span>':'◇';$('#stopButton').disabled=!state.available.includes('stop_action')||active.some(j=>j.command==='stop_action');document.querySelectorAll('[data-execute]').forEach(b=>{b.disabled=(!state.available.includes(b.dataset.execute)||!!action||state.unknownAction)&&b.dataset.execute!=='stop_action'})}
function render(){ $('#nav').innerHTML=Object.entries(groups).map(([key,g])=>`<button class="nav-item ${view===key?'active':''}" data-nav="${key}"><span class="nav-icon">${g[1]}</span><span>${g[0]}</span></button>`).join('');$('#crumb').textContent=groups[view][0];renderContent();updateDock() }
function renderContent(){if(view==='home'){renderHome();return}const c=commands[current];if(!c)return;$('#view').innerHTML=`<div class="page-head"><div><p class="eyebrow">ERINN / ${esc(view.toUpperCase())}</p><h1>${groups[view][0]}</h1><p class="muted">${view==='catalog'?'게임이 제공하는 기능을 확인하세요.':'지금 필요한 일을, 한곳에서.'}</p></div><span class="tag">AI 토큰 0</span></div><div class="tabs">${groups[view][2].map(x=>`<button data-tab="${x}" class="${current===x?'selected':''}">${commands[x][0]}</button>`).join('')}</div><section class="panel"><h2>${c[0]}</h2><p class="description">${c[1]}</p>${formFor(current)}</section><div id="results"></div>`;renderResults();}
function renderHome(){const env=cache.get_current_environment?.data||{}, me=cache.get_my_info?.data||{}, inv=cache.get_inventory?.data||{};const region=env.GameSpaceDisplayName||'연결을 확인하세요';const level=val(me.Level),job=val(me.EnabledCombatJobDisplayName);const weight=inv.CurrentInventoryWeightAsDecimal??inv.CurrentInventoryWeight;const max=inv.MaxInventoryWeightAsDecimal??inv.MaxInventoryWeight;$('#view').innerHTML=`<div class="page-head"><div><p class="eyebrow">YOUR EVERYDAY IN ERINN</p><h1>오늘도, 에린에서.</h1><p class="muted">모험의 현황을 살피고, 일상의 작업을 시작하세요.</p></div><span class="tag">LOCAL COMPANION</span></div><div class="hero"><div class="hero-copy"><p class="eyebrow">A LITTLE HELP FOR YOUR ADVENTURE</p><h2>모험은 가볍게,<br>일상은 여유롭게.</h2><p class="muted">채집부터 제작, 그리고 한 곡의 연주까지.<br>내가 고른 일을 게임 커넥터로 바로 실행하세요.</p><button class="primary" data-jump="get_daily_missions">오늘의 미션 확인하기 ↗</button></div><div class="hero-art" aria-hidden="true"><div class="sun"></div><div class="hill"></div><div class="hill second"></div><div class="hill third"></div><span class="star">✧</span></div></div><div class="stats">${[["현재 위치",region,env.Weather?text(env.Weather):'환경 조회 대기'],['캐릭터',level!==undefined?`Lv. ${text(level)}`:'—',job||'캐릭터 조회 대기'],['가방 무게',weight!==undefined?`${text(weight)} / ${text(max)}`:'—','마지막 조회 기준'],['연결 기능',state.available.length?`${state.available.length}개`:'—',online?'게임 커넥터 연결됨':'연결 확인 필요']].map(([a,b,c])=>`<div class="stat"><p class="stat-label">${a}</p><p class="stat-value">${esc(b)}</p><p class="stat-note">${esc(c)}</p></div>`).join('')}</div><div class="section-heading"><h2>어떤 일을 도와드릴까요?</h2><span class="muted" style="font-size:11px">선택한 기능만 실행됩니다</span></div><div class="quick-grid">${[['♧','채집과 낚시','필요한 재료와 도구를 확인하고 채집하기','get_gatherable_items'],['◇','제작과 가공','레시피를 살피고 작업을 등록하기','get_craftable_items'],['♫','악기와 연주','보유한 악보로 에린에 음악을 더하기','get_music_scores'],['▤','가방 정리 전 확인','재료와 소모품, 창고의 수량 확인하기','get_items'],['✧','일일 · 주간 미션','남은 목표와 완료 상태 확인하기','get_daily_missions'],['◷','가공 작업 현황','완료된 가공품과 남은 시간 확인하기','get_altering_works']].map(([icon,title,desc,cmd])=>`<button class="quick-card" data-jump="${cmd}"><span class="card-symbol">${icon}</span><h3>${title}</h3><p>${desc}</p></button>`).join('')}</div>`}
function formFor(cmd){const m=commands[cmd];const supported=cmd==='status'||cmd==='capabilities'||state.available.includes(cmd);const warning=!supported?'<div class="notice">현재 연결에서 이 기능을 확인하지 못했습니다. 연결 확인을 눌러 주세요.</div>':'';if(m[2]==='action'){let fields='';if(m[3]){const source=cache[m[3]]?.data;const rows=rowsOf(source);const names=[...new Set(rows.map(r=>r.DisplayName||r.DisplayTitle||r.Name).filter(Boolean))];fields=`<div class="toolbar"><label>대상 선택<select id="targetInput"><option value="">목록을 조회하고 대상을 선택하세요</option>${names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}</select></label>${cmd==='execute_crafting'?'<label class="compact">제작 횟수<input type="number" id="craftCount" min="1" max="100000" value="1"></label>':''}<button data-load="${m[3]}">대상 목록 불러오기</button></div>`;}return warning+fields+(m[5]?`<div class="notice">실행 1회당 정령의 날개 ${m[5]}개${cmd==='execute_crafting'?' · 횟수는 완성품 개수가 아닌 제작 횟수입니다.':''}${cmd==='execute_gathering'?' · 자동 낚시는 별도 중단이 필요합니다. 종료 후 자동 낚시 설정은 유지됩니다.':''}</div>`:'')+`<button class="primary" data-execute="${cmd}" style="margin-top:16px">${m[0]} ↗</button>`}if(m[2]==='chat')return warning+'<label>메시지 또는 행동 명령<textarea id="chatInput" maxlength="50" placeholder="보낼 문구를 입력하세요. 행동과 표정은 목록에서 선택할 수 있습니다."></textarea></label><p class="hint">최대 50자 · 전송 전 내용을 다시 확인합니다. 채널 변경 등의 예약 명령은 지원되지 않습니다.</p><button class="primary" data-execute="write_chat" style="margin-top:14px">내용 확인 후 실행 ↗</button>';return warning+`<div class="toolbar">${['filter','items'].includes(m[2])?'<label>이름으로 검색<input id="filterInput" placeholder="검색어를 입력하거나 비워 두세요" maxlength="500"></label>':''}${m[2]==='items'?'<label class="compact">분류<select id="categoryInput"><option value="">전체</option><option value="Ingredient">재료</option><option value="Food">음식</option><option value="Consumable">소모품</option><option value="Consumable_Box">상자</option><option value="Consumable_Growth">성장 소모품</option><option value="Quest">퀘스트</option></select></label>':''}<button class="primary" id="queryButton">${['filter','items'].includes(m[2])?'검색 / 전체 조회':'조회하기'} ↻</button></div>`}
function rowsOf(d){if(Array.isArray(d))return d;if(d?.items)return d.items;if(d?.works)return d.works;return []}
function errorText(j){const d=j.data;return j.error||errors[d?.error]||d?.message||d?.error||'요청에 실패했습니다. 원본 응답에서 자세한 내용을 확인하세요.'}
function details(d){if(d===null||d===undefined)return '<span class="muted">—</span>';if(typeof d!=='object')return esc(text(d));if(d.DisplayName&&'Value'in d)return `<dl class="kv"><dt>${esc(d.DisplayName)}</dt><dd>${esc(text(d.Value))}</dd></dl>`;if(Array.isArray(d)){return d.length?d.map(x=>`<div class="kv-group">${details(x)}</div>`).join(''):'<span class="muted">없음</span>'}return Object.entries(d).map(([k,v])=>{if(v&&typeof v==='object'){if(v.DisplayName&&'Value'in v)return details(v);return `<div class="kv-group"><h3>${esc(labels[k]||k)}</h3>${details(v)}</div>`}return `<dl class="kv"><dt>${esc(labels[k]||k)}</dt><dd>${esc(text(v))}</dd></dl>`}).join('')}
function renderResults(){const el=$('#results');if(!el)return;const j=cache[current];if(!j){el.innerHTML='<div class="empty"><span class="empty-icon">⌕</span><p>조회 버튼을 누르면 게임의 최신 정보를 가져옵니다.</p></div>';return}rawData=j.raw??j.data??j;let html=`<div class="result-title"><h3>${j.ok?'조회 / 실행 결과':jobStatus(j)}</h3><div class="result-actions"><span class="muted">${new Date((j.finished||j.started)*1000).toLocaleTimeString('ko-KR')}</span><button id="exportButton" class="small">JSON 저장</button></div></div>`;if(!j.ok)html+=`<div class="notice">${esc(errorText(j))}</div>`;const d=j.data;if(current==='capabilities'&&d?.commands){html+=d.loading?'<div class="notice">게임 로딩 중입니다. 캐릭터 접속 후 다시 조회하세요.</div>':'';html+=d.commands.map(c=>`<details class="catalog-row"><summary>${esc(commands[c.Command]?.[0]||c.Command)} <span class="pill">${actionCmd(c.Command)?'실행':'조회'}</span><code>${esc(c.Command)}</code></summary><p>${esc(c.Description)}</p><pre>${esc(JSON.stringify(c,null,2))}</pre>${commands[c.Command]?`<button data-jump="${esc(c.Command)}" class="small">기능 열기 ↗</button>`:''}</details>`).join('')}else if(current==='get_social_actions'&&d){html+=`<div class="result-grid">${[...(d.Behaviours||[]).flatMap(a=>(a.ChatCommands||[]).map(c=>({name:a.DisplayName,command:c}))),...(d.Facials||[]).map(a=>({name:a.DisplayName,command:a.EmojiText}))].map(a=>`<div class="result-card"><h3>${esc(a.name)}</h3><p>${esc(a.command)}</p><button class="primary" data-social="${esc(a.command)}">확인 후 실행</button></div>`).join('')}</div>`}else{const list=rowsOf(d);if(Array.isArray(d)||d?.items||d?.works){if(d?.craftingUnlocked===false)html+='<div class="notice">게임에서 제작 기능을 먼저 해금해야 합니다.</div>';if(d?.completedCount!==undefined)html+=`<p class="description">수령 가능한 작업 ${d.completedCount}건 · 수령은 선택한 시설 단위로 진행됩니다.</p>`;html+=list.length?`<div class="result-grid">${list.slice(page*36,(page+1)*36).map((row,index)=>rowCard(row,page*36+index)).join('')}</div>`:'<div class="empty"><span class="empty-icon">◇</span><p>표시할 항목이 없습니다. 검색어와 게임 상태를 확인하세요.</p></div>';if(list.length>36)html+=`<div class="pagination"><button data-page="${page-1}" ${page===0?'disabled':''}>이전</button><span>${page+1} / ${Math.ceil(list.length/36)} · ${list.length}개</span><button data-page="${page+1}" ${(page+1)*36>=list.length?'disabled':''}>다음</button></div>`}else if(d!==undefined)html+=`<div class="panel">${details(d)}</div>`}html+=`<details class="raw-details"><summary>원본 응답 보기</summary><pre>${esc(JSON.stringify(rawData,null,2))}</pre></details>`;el.innerHTML=html;updateDock()}
function rowCard(r,index){if(!r||typeof r!=='object')return `<div class="result-card">${esc(text(r))}</div>`;let title=r.DisplayName||r.DisplayTitle||r.Name||r.QuestTitle||r.Title||`항목 ${index+1}`;if(current==='get_near_pcs')title=`주변 모험가 ${index+1}`;let html=`<div class="result-card"><h3>${esc(title)}</h3>`;const mission=current.endsWith('_missions');if(mission){const done=!!r.IsCompleted;html+=`<span class="pill ${done?'':'warn'}">${r.IsRewardReceived?'보상 수령':done?'완료 · 보상 미수령':'진행 중'}</span><p>${esc(r.Description)}</p><p>${r.CurrentCount} / ${r.GoalCount}</p><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,Math.max(0,100*r.CurrentCount/(r.GoalCount||1)))}%"></div></div>`}else{const omit=new Set(['DisplayName','DisplayTitle','Name','QuestTitle','Category','Source']);for(const [k,v]of Object.entries(r)){if(omit.has(k)||k==='Title'&&current!=='get_near_pcs')continue;if(typeof v==='boolean')html+=`<span class="pill ${v?'':'warn'}">${esc(labels[k]||k)} ${v?'✓':'—'}</span>`;else if(v!==null&&typeof v!=='object')html+=`<p>${esc(labels[k]||k)} · ${esc(k==='Reason'?(errors[v]||text(v)):text(v))}</p>`;else if(v&&((Array.isArray(v)&&v.length)||!Array.isArray(v)))html+=`<details class="raw-details"><summary>${esc(labels[k]||k)}</summary>${details(v)}</details>`;}}
const next={get_gatherable_items:['execute_gathering','채집 시작',r.ToolOk],get_craftable_items:['execute_crafting','제작하기',r.Craftable],get_alterable_items:['execute_altering','가공 등록',r.Alterable],get_altering_works:['complete_altering_work','이 시설의 완료 작업 수령',r.IsCompleted],get_instruments:['change_instrument',r.IsEquipped?'장착 중':'장착하기',!r.IsEquipped],get_music_scores:['play_music_score','연주하기',true]}[current];if(next){html+=`<button class="primary" data-row="${index}" data-next="${next[0]}" ${next[2]===false?'disabled':''}>${next[1]}${commands[next[0]][5]?' · 날개 5':''}</button>`}return html+'</div>'}
async function confirmAction(cmd,body){if(confirmationBusy)return false;confirmationBusy=true;const c=commands[cmd];$('#confirmTitle').textContent=c[0];$('#confirmText').textContent=c[1]+(c[5]?` 정령의 날개 ${c[5]}개가 소비됩니다.`:'');$('#confirmTarget').textContent=typeof body==='string'?(body||'현재 캐릭터의 행동에 적용됩니다.'):(Object.entries(body).map(([k,v])=>`${k==='craftCount'?'제작 횟수':'대상'}: ${v}`).join('\n'));const dialog=$('#confirmDialog');dialog.returnValue='cancel';dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>{confirmationBusy=false;resolve(dialog.returnValue==='ok')},{once:true}))}
async function execute(cmd,body){if(!state.available.includes(cmd)){toast('연결 확인 후 다시 시도하세요.');return}if(!await confirmAction(cmd,body))return;try{const promise=request(cmd,body,true);toast('게임에 실행을 요청했습니다. 하단에서 진행 상태를 확인하세요.');const j=await promise;if(current!==cmd&&j.state!=='running')toast(`${commands[cmd][0]}: ${j.ok?jobStatus(j):errorText(j)}`)}catch(e){toast(e.message)}}
async function query(){const cmd=current;let body='';if(commands[cmd][2]==='filter')body=$('#filterInput').value.trim();if(commands[cmd][2]==='items')body=Object.fromEntries([['name',$('#filterInput').value.trim()],['category',$('#categoryInput').value]].filter(([,v])=>v));const b=$('#queryButton');if(b)b.disabled=true;$('#results').innerHTML='<div class="loading"><span class="spinner"></span>게임에서 정보를 가져오고 있습니다.</div>';try{page=0;await request(cmd,body)}catch(e){toast(e.message);if(current===cmd)renderResults()}finally{if($('#queryButton'))$('#queryButton').disabled=false}}
function renderHistory(){$('#historyList').innerHTML=state.jobs.slice().reverse().map(j=>`<details class="history-row"><summary><span class="pill ${j.state==='failed'?'bad':j.state==='running'?'warn':''}">${jobStatus(j)}</span><b>${esc(commands[j.command]?.[0]||j.command)}</b><span>${new Date(j.started*1000).toLocaleTimeString('ko-KR')}</span></summary>${j.error?`<p class="error-text">${esc(j.error)}</p>`:''}<pre>${esc(JSON.stringify({입력:j.body,결과:j.raw??j.data??null},null,2))}</pre></details>`).join('')||'<div class="empty">아직 요청 기록이 없습니다.</div>'}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;try{if(b.dataset.nav)go(b.dataset.nav);else if(b.dataset.tab){current=b.dataset.tab;page=0;renderContent()}else if(b.dataset.jump)navigateCommand(b.dataset.jump);else if(b.id==='queryButton')await query();else if(b.dataset.page!==undefined){page=+b.dataset.page;renderResults()}else if(b.dataset.load){b.disabled=true;await request(b.dataset.load);renderContent()}else if(b.dataset.next){const row=rowsOf(cache[current]?.data)[+b.dataset.row];const cmd=b.dataset.next;const name=row.DisplayName||row.DisplayTitle||row.Name;navigateCommand(cmd);$('#targetInput').value=name;}else if(b.dataset.social){navigateCommand('write_chat');$('#chatInput').value=b.dataset.social;}else if(b.dataset.execute){const cmd=b.dataset.execute,m=commands[cmd];let body='';if(m[3]){const name=$('#targetInput').value;if(!name)return toast('대상을 선택하세요.');body={[m[4]]:name};if(cmd==='execute_crafting'){body.craftCount=Number($('#craftCount').value);if(!Number.isInteger(body.craftCount)||body.craftCount<1)return toast('제작 횟수를 확인하세요.')}}if(cmd==='write_chat'){body=$('#chatInput').value.trim();if(!body)return toast('메시지를 입력하세요.')}await execute(cmd,body);}else if(b.id==='stopButton')await execute('stop_action','');else if(b.id==='connectButton')await connect();else if(b.id==='historyButton'){renderHistory();$('#historyDialog').showModal()}else if(b.id==='closeHistory')$('#historyDialog').close();else if(b.id==='settingsButton'){$('#cliPath').value=state.cli||'';$('#settingsDialog').showModal()}else if(b.id==='closeSettings')$('#settingsDialog').close();else if(b.id==='quitButton'){if(confirm('에린 데스크를 종료할까요? 게임 자체는 종료되지 않습니다.')){await api('/api/shutdown',{});stopped=true;clearTimeout(pollTimer);$('#banner').hidden=true;$('#view').innerHTML='<div class="empty"><h2>에린 데스크를 종료했습니다.</h2><p>이 탭을 닫아도 됩니다.</p></div>';$('#connection').textContent='앱 종료됨';}}else if(b.id==='exportButton'){const blob=new Blob([JSON.stringify(rawData,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`erinn-${current}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}catch(error){toast(error.message);if(b.dataset.load)b.disabled=false}});
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/settings',{cli:$('#cliPath').value});$('#settingsDialog').close();await connect()}catch(error){$('#settingsError').textContent=error.message}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='filterInput')query()});
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(groups[v]&&v!==view)go(v)});
const initial=location.hash.slice(1);if(groups[initial]){view=initial;current=groups[view][2][0]||''}render();
$('#mobileSettings').addEventListener('click',()=>$('#settingsButton').click());
$('#mobileQuit').addEventListener('click',()=>$('#quitButton').click());

window.startBridgeSession=async()=>{if(busyPolling)throw new Error('잠시 후 다시 연결하세요.');for(const p of waiters.values())p.reject(new Error('연결을 다시 설정했습니다.'));waiters.clear();clearTimeout(pollTimer);stopped=false;cache={};handled.clear();state={jobs:[],available:[],catalog:{}};online=false;await poll();await connect();};
